apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: podtato-head
  name: podtato-head-right-arm
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: podtato-head-right-arm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: podtato-head-right-arm
    spec:
      containers:
      - env:
        - name: PODTATO_PORT
          value: "9000"
        image: ghcr.io/podtato-head/right-arm:latest
        imagePullPolicy: Always
        name: server
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
